blank_issues_enabled: true
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ ë° í† ë¡ 
    url: https://github.com/ticket-project/ticket-be/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”.